# Generated by Django 4.0.4 on 2022-06-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
