# Generated by Django 4.0.4 on 2022-06-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppForms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
