# Generated by Django 4.0.4 on 2022-06-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppForms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='create_dt',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='create_dt',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='create_dt',
        ),
    ]
