# Generated by Django 4.0.4 on 2022-06-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppForms', '0002_curso_is_active_estudiante_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='is_active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='is_active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='is_active',
            new_name='activo',
        ),
    ]
