# Generated by Django 4.0.4 on 2022-06-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppForms', '0002_remove_curso_create_dt_remove_estudiante_create_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='camada',
            new_name='comision',
        ),
    ]
